/*
 * This file was generated by Mountaineer v0.1.0. Do not edit it manually.
 */

import { __request, FetchErrorBase } from '../../../_server/api';
import type {  } from '../../../_server/controllers';