/*
 * This file was generated by Mountaineer v0.1.0. Do not edit it manually.
 */

import { __getLink } from '../../../_server/api';



export const getLink = ({
  exception,
  stack
}: {
  exception: string,
  stack: string
}) => {
  const url = `/_exception`;

  const queryParameters: Record<string, any> = {
    exception,
    stack
  };
  const pathParameters: Record<string, any> = {

  };

  return __getLink({
    rawUrl: url,
    queryParameters,
    pathParameters
  });
};